version: '3.9'

services:
  # Execution du dockerfile
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8010:80"





volumes:
  db_data: {}

networks:
  MyDevStack: {}