version: '3.9'

services:
  pile-php-apache:
    container_name: php-apache
    image: webdevops/php-apache-dev:8.2-alpine
    volumes:
      - ./angular-nginx-docker:/app/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: mastack_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: userPass
    ports:
      - "9906:3306"
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
  # Execution du dockerfile
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 4200:4200
    volumes:
      - .:/app
    command:
      - ng serve --host 0.0.0.0
  nginx:
    image: angular-nginx-docker
    ports:
      - "8010:80"





volumes:
  db_data: {}

networks:
  MyDevStack: {}